import { cfpLink } from './config'

export const speakersList = [
  {
    imageUrl: '/static/speakers/peggy-rayzis',
    imageFormat: 'jpg',
    name: 'Peggy Rayzis',
    bio: 'Open Source Engineer @ Apollo',
    twitter: 'peggyrayzis',
    github: 'peggyrayzis',
  },
  {
    imageUrl: '/static/speakers/lee-byron',
    imageFormat: 'jpg',
    name: 'Lee Byron',
    bio: 'Facebook, GraphQL co-creator',
    twitter: 'leeb',
    github: 'leebyron',
  },
  {
    imageUrl: '/static/speakers/nick-schrock',
    imageFormat: 'jpg',
    name: 'Nick Schrock',
    bio: 'Ex-Facebook Engineer, GraphQL co-creator',
    twitter: 'schrockn',
    github: 'schrockn',
  },
  {
    imageUrl: '/static/speakers/johannes-schickling',
    imageFormat: 'jpg',
    name: 'Johannes Schickling',
    bio: 'CEO & Founder @ Prisma',
    twitter: '_schickling',
    github: 'schickling',
  },
  {
    imageUrl: '/static/speakers/nicholas-van-wiggeren',
    imageFormat: 'jpeg',
    name: 'Nicholas Van Wiggeren',
    bio: 'Github',
    twitter: 'NickVanWig',
    github: 'nickvanw',
  },
  {
    imageUrl: '/static/speakers/sara-vieira',
    imageFormat: 'jpg',
    name: 'Sara Vieira',
    bio: 'Frontend Engineer @ YLD.io',
    twitter: 'NikkitaFTW',
    github: 'SaraVieira',
  },
  {
    imageUrl: '/static/speakers/jira-vinyoopongphan',
    imageFormat: 'jpg',
    name: 'Jira Vinyoopongphan',
    bio: 'Frontend Engineer @ Capital One',
    twitter: 'thekamahele',
    github: 'thekamahele',
  },
  {
    imageUrl: '/static/speakers/leanne-shapton',
    imageFormat: 'png',
    name: 'Leanne Shapton',
    bio: 'Software Engineer @ Shopify',
    twitter: 'leeshapton',
    github: 'lshapton',
  },
  {
    imageUrl: '/static/speakers/arnaud-rinquin',
    imageFormat: 'jpg',
    name: 'Arnaud Rinquin',
    bio: 'Developer @ Slite',
    twitter: 'arnaudrinquin',
    github: 'arnaudrinquin',
  },
  {
    imageUrl: '/static/speakers/daniel-woelfel',
    imageFormat: 'jpg',
    name: 'Daniel Woelfel',
    bio: 'Software Engineer @ Facebook',
    twitter: 'DanielWoelfel',
    github: 'dwwoelfel',
  },
  {
    imageUrl: '/static/speakers/david-krentzlin',
    imageFormat: 'jpg',
    name: 'David Krentzlin',
    bio: 'Software Engineer @ Xing',
    twitter: 'dkrentzlin',
    github: 'certainty',
  },
  {
    imageUrl: '/static/speakers/jon-wong',
    imageFormat: 'jpg',
    name: 'jon-wong',
    bio: 'Frontend Infrastructure Engineer @ Coursera',
    twitter: 'jnwng',
    github: 'jnwng',
  },
  {
    imageUrl: '/static/speakers/michael-hunger',
    imageFormat: 'jpg',
    name: 'Michael Hunger',
    bio: 'Head of Developer Relations @ Neo4j',
    twitter: 'mesirii',
    github: 'jexp',
  },
  {
    imageUrl: '/static/speakers/mike-solomon',
    imageFormat: 'jpg',
    name: 'Mike Solomon',
    bio: 'Software Engineer @ Twitter',
    twitter: 'msol',
    github: 'msolomon',
  },
  {
    imageUrl: '/static/speakers/olaf-hartig',
    imageFormat: 'jpg',
    name: 'Olaf Hartig',
    bio: 'Assistant Professor for CS @ Linköping University',
    twitter: 'olafhartig',
    github: 'hartig',
  },
  {
    imageUrl: '/static/speakers/rob-richard',
    imageFormat: 'jpg',
    name: 'Rob Richard',
    bio: 'Frontend Engineering Director @ 1stdibs',
    github: 'robrichard',
  },
  {
    imageUrl: '/static/speakers/sasha-solomon',
    imageFormat: 'jpg',
    name: 'Sasha Solomon',
    bio: 'Tech Lead @ Medium',
    twitter: 'sachee',
    github: 'sachee',
  },
  {
    imageUrl: '/static/speakers/stephen-wan',
    imageFormat: 'jpg',
    name: 'Stephen Wan',
    bio: 'Software Engineer @ Samsara',
    twitter: 'stpnwn',
    github: 'stephen',
  },
  {
    imageUrl: '/static/speakers/tyler-martinez',
    imageFormat: 'jpg',
    name: 'Tyler Martinez',
    bio: 'Software Engineer @ Docker',
    twitter: 'slightlytyler',
    github: 'slightlytyler',
  },
]
